[build]
  command = "CI= npm run build"  # Add CI= to prevent warnings from failing build
  publish = "build"  # Or "dist" depending on your framework

[build.environment]
  NODE_VERSION = "18.12.1"  # Stable LTS version